- name: "Add nodejs from node source"
  become: true
  shell: |
    curl -fsSL -O https://deb.nodesource.com/setup_13.x | sudo -E bash -
- name: "Install Nodejs 13"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes
- name: "install pm2"
  npm:
    name: pm2
    global: yes

