## Deployment playbook goes here.
name: un tar the file
become: yes
command: |
  tar -xzvf artifact.tar.gz 

name: start the app
become: yes
command: |
  npm install
  pm2 stop default
  pm2 start npm -- start
